# Form implementation generated from reading ui file '/Users/laurentletourneau-guillon/Dropbox (Personal)/CHUM/RECHERCHE/2020BahigENE/GGGTV_Bahig/GGGTV_Bahig/gtvgg_seg-main/Resources/UI/ICH_SEGMENTER_GGTV.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


